baseURL = "https://panzersoft.com/"
languageCode = "en-us"
title = "PanzerSoftのホームページ"
Copyright = "© PanzerSoft All Rights Reserved."

DisqusShortname="panzersoft"

[Params]
logotype = '<span class="has-text-weight-bold site-title">Panzer<span class="has-text-danger">Soft</span></span>'
#'PanzerSoft'
fullname = "同人ゲームサークル panzerSoft のホームページへようこそ"
footer = "This site is made by satoya<br>"
subfooter = "<a href='blog'>blog</a> | <a href='project'>projects</a> | <a href='tags'>tags</a>| <a href='http://www.dlsite.com/maniax/circle/profile/=/maker_id/RG20019.html'>dlsite</a> | <a href='https://www.dmm.co.jp/dc/doujin/-/list/=/article=maker/id=28305/'>dmm</a> | <a href='https://www.pixiv.net/member.php?id=6038674'>pixiv</a> | <a href='https://github.com/yano'>github</a> | <a href='https://twitter.com/satoya_123'>twitter</a><br>"
debug = false

[menu]

  [[menu.sectionmenu]]
  name = "About"
  url = "about/"
  identifier = "about"
  weight = 10.0

  [[menu.sectionmenu]]
  name = "Blog"
  url = "blog/"
  weight = 30.0

  [[menu.sectionmenu]]
  name = "Projects"
  url = "project/"
  identifier = "project"
  weight = 20.0

  [[menu.sectionmenu]]
  name = "プリシアディフェンス"
  url = "project/priciadefence/"
  parent = "project"
  weight = 203.0

  [[menu.sectionmenu]]
  name = "Desktop Mascot Maker (日本語)"
  url = "project/desktopmascotmaker/ja/"
  parent = "project"
  weight = 204.0

  [[menu.sectionmenu]]
  name = "Desktop Mascot Maker (English)"
  url = "project/desktopmascotmaker/en/"
  parent = "project"
  weight = 205.0

