baseURL = "https://panzersoft.com/"
languageCode = "en-us"
title = "PanzerSoftのホームページ"
Copyright = "© PanzerSoft All Rights Reserved."

[Params]
logotype = '<span class="has-text-weight-bold">Panzer<span class="has-text-info">Soft</span></span>'
#'PanzerSoft'
fullname = "同人ゲームサークル panzerSoft のホームページへようこそ"
footer = "This site is made by satoyan"
subfooter = "twitter"

[menu]

  [[menu.sectionmenu]]
  name = "About"
  url = "about/"
  identifier = "about"
  weight = 10.0

  [[menu.sectionmenu]]
  name = "Contact Us"
  url = "about/contact/"
  parent = "about"
  weight = 101.0

  [[menu.sectionmenu]]
  name = "Projects"
  url = "project/"
  identifier = "project"
  weight = 20.0

  [[menu.sectionmenu]]
  name = "Hugo-Smorg"
  url = "project/hugo-smorg/"
  parent = "project"
  weight = 201.0

  [[menu.sectionmenu]]
  name = "Blorg Bread Machine"
  url = "project/blorg-bread-machine/"
  parent = "project"
  weight = 202.0

  [[menu.sectionmenu]]
  name = "XYZ-1000"
  url = "project/xyz-1000/"
  parent = "project"
  weight = 203.0

  [[menu.sectionmenu]]
  name = "Blog"
  url = "post/"
  weight = 30.0

