baseURL = "https://panzersoft.com/"
languageCode = "en-us"
title = "PanzerSoftのホームページ"
Copyright = "© PanzerSoft All Rights Reserved."

DisqusShortname="panzersoft"

[Params]
logotype = '<span class="has-text-weight-bold site-title">Panzer<span class="has-text-danger">Soft</span></span>'
#'PanzerSoft'
fullname = "同人ゲームサークル panzerSoft のホームページへようこそ"
footer = "This site is made by satoya<br>"
subfooter = "<a href='post'>blog</a> | <a href='project'>projects</a> | <a href='tags'>tags</a> | <a href='categories'>categories</a> | <a href='http://www.dlsite.com/maniax/circle/profile/=/maker_id/RG20019.html'>dlsite</a> | <a href='https://www.dmm.co.jp/dc/doujin/-/list/=/article=maker/id=28305/'>dmm</a> | <a href='https://github.com/yano'>github</a> | <a href='https://twitter.com/satoya_123'>twitter</a><br>"

[menu]

  [[menu.sectionmenu]]
  name = "About"
  url = "about/"
  identifier = "about"
  weight = 10.0

  [[menu.sectionmenu]]
  name = "Contact Us"
  url = "about/contact/"
  parent = "about"
  weight = 101.0

  [[menu.sectionmenu]]
  name = "Blog"
  url = "post/"
  weight = 30.0

  [[menu.sectionmenu]]
  name = "Projects"
  url = "project/"
  identifier = "project"
  weight = 20.0

  [[menu.sectionmenu]]
  name = "Hugo-Smorg"
  url = "project/hugo-smorg/"
  parent = "project"
  weight = 201.0

  [[menu.sectionmenu]]
  name = "Blorg Bread Machine"
  url = "project/blorg-bread-machine/"
  parent = "project"
  weight = 202.0

  [[menu.sectionmenu]]
  name = "XYZ-1000"
  url = "project/xyz-1000/"
  parent = "project"
  weight = 203.0

  [[menu.sectionmenu]]
  name = "プリシア"
  url = "project/pricia/"
  parent = "project"
  weight = 204.0
